## List Samples

* 1D - one diminsion
* Heterogenous - allow mulityple data type
* Accept duplicate values
* Indexing and slicing is possible
* Mutable - value can be changed in list , add, update, clear, 
* print items items left to right

In [1]:
empty_list=[]  #empty list

In [2]:
type(empty_list) #get data type

list

In [3]:
products = ["Laptop", "Mouse", "Keyboard"]
for product in products:
    print(product) #print list items

Laptop
Mouse
Keyboard

In [4]:
print(products[0]) # get data by index

Laptop

In [6]:
print(products[1:3]) # get data by slicing

['Mouse', 'Keyboard']

In [10]:
products = ["Laptop", "Mouse", "Keyboard",1.3,1,22,9.0]
for product in products:
    print(product) #print list items by index from left to right

Laptop
Mouse
Keyboard
1.3
1
22
9.0

In [11]:
products[3]="Monitor"
for product in products:
    print(product) #print list items by index from left to right

Laptop
Mouse
Keyboard
Monitor
1
22
9.0

### Function in list

##### append() Adds an element at the end of the list

In [12]:
products = ["Laptop", "Mouse", "Keyboard"]

products.append("Monitor")

for product in products:
    print(product) #print list items

Laptop
Mouse
Keyboard
Monitor

In [13]:
sales = [1200, 1500, 1800, 2000]

total = 0

for amount in sales:
    total += amount

print("Total Sales:", total)

Total Sales: 6500

In [14]:
sales.append(3000)

In [15]:
total = 0

for amount in sales:
    total += amount

print("Total Sales:", total)

Total Sales: 9500

In [17]:
orders = ["ORD101", "ORD102", "ORD103"]
orders.append("ORD104")

for order in orders:
    print("Processing:", order)

Processing: ORD101
Processing: ORD102
Processing: ORD103
Processing: ORD104

##### clear()  - Removes all the elements from the list

In [19]:
orders.clear()
print("Processing:", orders)

Processing: []

##### copy() - Returns a copy of the list

In [20]:
orders = ["ORD101", "ORD102", "ORD103"]
for order in orders:
    print("Processing:", order)

Processing: ORD101
Processing: ORD102
Processing: ORD103

In [22]:
final_orders = orders.copy() # copy orders list to final_orders 

for order in final_orders:
    print("Processing:",order)

Processing: ORD101
Processing: ORD102
Processing: ORD103

#####  count() - Returns the number of elements with the specified value

In [23]:
print(final_orders.count)

<built-in method count of list object at 0x000002BBB5D9A600>

In [24]:
print(final_orders.count)

TypeError: list.count() takes exactly one argument (0 given)

In [26]:
print(final_orders.count("ORD103"))

1

In [29]:
final_orders.append("ORD103")

In [30]:
print(final_orders.count("ORD103"))  # returns how many time particular item count

2

##### extend() - Adds multiple items to the end of the list.

In [31]:
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD103']

In [32]:
final_orders.extend('ORD104','ORD105') #error
final_orders

TypeError: list.extend() takes exactly one argument (2 given)

In [33]:
final_orders.extend(['ORD104','ORD105']) # add as list
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD103', 'ORD104', 'ORD105']

##### insert() - Inserts an item at a specified position.

In [34]:
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD103', 'ORD104', 'ORD105']

In [39]:
final_orders.insert(1,'ORD102_d')
final_orders

['ORD101', 'ORD102_d', 'ORD102', 'ORD103', 'ORD103', 'ORD104', 'ORD105']

##### remove() Removes the first matching item.

In [36]:
final_orders

['ORD101', 'ORD102_d', 'ORD102', 'ORD103', 'ORD103', 'ORD104', 'ORD105']

In [40]:
final_orders.remove('ORD102_d') 
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD103', 'ORD104', 'ORD105']

#####  pop() - Removes an item by index and returns it.

In [41]:
final_orders
final_orders.pop(2)
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD104', 'ORD105']

##### index() Returns the index of the first matching item.

In [45]:
final_orders.index('ORD103')

2

#####  sort() - Sorts the list in ascending order.

In [46]:
final_orders.sort()
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD104', 'ORD105']

In [47]:
final_orders.insert(1,'ORD106')
final_orders

['ORD101', 'ORD106', 'ORD102', 'ORD103', 'ORD104', 'ORD105']

In [48]:
final_orders.sort()
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD104', 'ORD105', 'ORD106']

##### sort(reverse=True) Sorts in descending order.

In [49]:
final_orders.sort(reverse=True)
final_orders

['ORD106', 'ORD105', 'ORD104', 'ORD103', 'ORD102', 'ORD101']

##### reverse() Reverses the order of the list.

In [50]:
final_orders.sort()
final_orders

['ORD101', 'ORD102', 'ORD103', 'ORD104', 'ORD105', 'ORD106']

In [51]:
final_orders.reverse()
final_orders

['ORD106', 'ORD105', 'ORD104', 'ORD103', 'ORD102', 'ORD101']

##### len() Returns the number of items in a list.

In [52]:
final_orders

['ORD106', 'ORD105', 'ORD104', 'ORD103', 'ORD102', 'ORD101']

In [53]:
len(final_orders)

6

##### min() Returns the smallest value.

In [54]:
marks = [80, 65, 90, 75]

print(min(marks))

65

##### max() Returns the largest value

In [55]:
marks = [80, 65, 90, 75]

print(max(marks))

90

##### sum() Returns the total of all numeric values.

In [56]:
sales = [1200, 1500, 1800]

print(sum(sales))

4500

##### sorted() Returns a new sorted list without changing the original.

In [57]:
numbers = [30, 10, 20]

new_list = sorted(numbers)

print(new_list)
print(numbers)

[10, 20, 30]
[30, 10, 20]

## Sets

* 1D - one diminsion
* Heterogenous - allow mulityple data type
* It won't allow duplicate values
* Indexing and slicing is not possible
* Mutable - value can be changed in list , add, update, clear,

In [60]:
set_empty_cart=set()
type(set_empty_cart)

set

In [61]:
numbers = {10, 20, 30, 20}
print(numbers) #remove duplicate values

{10, 20, 30}

In [62]:
products = {"Laptop", "Mouse", "Keyboard"}
products

{'Keyboard', 'Laptop', 'Mouse'}

In [63]:
products = {"Laptop", "Mouse", "Keyboard","Mouse"}
products

{'Keyboard', 'Laptop', 'Mouse'}

In [64]:
products = {"Laptop", "Mouse", "Keyboard","Mouse",2,33.3}
products  # Heterogenous - allow mulityple data type

{2, 33.3, 'Keyboard', 'Laptop', 'Mouse'}

##### remove() Removes an element. Raises an error if it doesn't exist.

In [65]:
products.remove(2)
products

{33.3, 'Keyboard', 'Laptop', 'Mouse'}

In [66]:
products.remove(33.3)
products

{'Keyboard', 'Laptop', 'Mouse'}

##### add() Adds a single element to a set.

In [67]:
products.add("Monitor")
products

{'Keyboard', 'Laptop', 'Monitor', 'Mouse'}

##### update() Adds multiple elements from another collection.

In [68]:
products.update(["Note Pad","Pen"])
products # add add from list to set

{'Keyboard', 'Laptop', 'Monitor', 'Mouse', 'Note Pad', 'Pen'}

##### discard()  - Removes an element if it exists. Does not raise an error if it doesn't.

In [69]:
products.discard("pen") #lower case not matched

In [70]:
products

{'Keyboard', 'Laptop', 'Monitor', 'Mouse', 'Note Pad', 'Pen'}

In [71]:
products.discard("Pen")
products

{'Keyboard', 'Laptop', 'Monitor', 'Mouse', 'Note Pad'}

##### pop() Removes and returns a random element.

In [72]:
products

{'Keyboard', 'Laptop', 'Monitor', 'Mouse', 'Note Pad'}

In [73]:
item = products.pop()

In [74]:
item

'Monitor'

In [75]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

##### copy() Creates a copy of a set.

In [128]:
set1 = {10, 20, 30}

set2 = set1.copy()

print(set2)

{10, 20, 30}

In [76]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [77]:
final_products_lsit = products.copy()

In [78]:
final_products_lsit

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

##### union() Returns all unique elements from both sets.

In [127]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

print(set1.union(set2))

{1, 2, 3, 4, 5}

In [79]:
final_products_lsit.update(['Book','File','Mouse Pad']) # add few more items

In [80]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [81]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [82]:
print(products.union(final_products_lsit)) # union - function

{'Note Pad', 'File', 'Mouse', 'Mouse Pad', 'Keyboard', 'Book', 'Laptop'}

##### intersection() Returns common elements.

In [126]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}

print(set1.intersection(set2))

{2, 3}

In [83]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [84]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [85]:
print(products.intersection(final_products_lsit))

{'Mouse', 'Keyboard', 'Laptop', 'Note Pad'}

##### difference() Returns elements present only in the first set.

In [125]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}

print(set1.difference(set2))

{1}

In [86]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [87]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [88]:
print(products.difference(final_products_lsit))

set()

In [89]:
print(final_products_lsit.difference(products))

{'Book', 'File', 'Mouse Pad'}

##### symmetric_difference() Returns elements that are in either set, but not both.

In [124]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}

print(set1.symmetric_difference(set2))

{1, 4}

In [123]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [91]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [92]:
print(products.symmetric_difference(final_products_lsit))

{'Book', 'Mouse Pad', 'File'}

##### issubset() Checks whether one set is a subset of another.

In [122]:
set1 = {1, 2}
set2 = {1, 2, 3, 4}

print(set1.issubset(set2))

True

In [93]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [94]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [95]:
print(products.issubset(final_products_lsit))

True

In [96]:
print(final_products_lsit.issubset(products))

False

##### issuperset() Checks whether one set contains another.

In [121]:
set1 = {1, 2, 3, 4}
set2 = {1, 2}

print(set1.issuperset(set2))

True

In [97]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [98]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [99]:
print(products.issuperset(final_products_lsit))

False

In [100]:
print(final_products_lsit.issuperset(products))

True

##### isdisjoint() Checks whether two sets have no common elements.

In [101]:
products

{'Keyboard', 'Laptop', 'Mouse', 'Note Pad'}

In [102]:
final_products_lsit

{'Book', 'File', 'Keyboard', 'Laptop', 'Mouse', 'Mouse Pad', 'Note Pad'}

In [103]:
print(products.isdisjoint(final_products_lsit))

False

In [104]:
print(final_products_lsit.isdisjoint(products))

False

In [105]:
set1 = {1, 2}
set2 = {3, 4}

print(set1.isdisjoint(set2))

True

##### intersection_update Updates the set with only common elements.

In [106]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}

set1.intersection_update(set2)

print(set1)

{2, 3}

In [107]:
set1

{2, 3}

In [108]:
set2

{2, 3, 4}

##### difference_update() Removes common elements from the first set.

In [109]:
set1 = {1, 2, 3}
set2 = {2, 3}

In [110]:
set1

{1, 2, 3}

In [111]:
set2

{2, 3}

In [112]:

set1.difference_update(set2)

print(set1)

{1}

In [113]:
set1

{1}

In [114]:
set2

{2, 3}

##### symmetric_difference_update() Updates the set with elements that are unique to each set.

In [115]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

In [116]:
set1

{1, 2, 3}

In [117]:
set2

{3, 4, 5}

In [118]:
set1.symmetric_difference_update(set2)

In [119]:
set1

{1, 2, 4, 5}

In [120]:
set2

{3, 4, 5}

## Tuple ()

* 1D - one diminsion
* Heterogenous - allow mulityple data type
* Accept duplicate values
* Indexing and slicing is possible
* Immutable - value can be changed in list

In [129]:
empty_cart_3 = ()
type(empty_cart_3)

tuple

In [132]:
products_tuple = ("Laptop", "Mouse", "Keyboard","Mouse")
products_tuple

('Laptop', 'Mouse', 'Keyboard', 'Mouse')

#####  count() - Counts how many times an element appears.

In [134]:
products_tuple

('Laptop', 'Mouse', 'Keyboard', 'Mouse')

In [135]:
print(products_tuple.count("Mouse"))

2

##### index() Returns the index of the first occurrence.

In [136]:
products_tuple

('Laptop', 'Mouse', 'Keyboard', 'Mouse')

In [137]:
print(products_tuple.index("Mouse"))

1

##### len() (Built-in Function) - Returns the number of elements.

In [138]:
products_tuple

('Laptop', 'Mouse', 'Keyboard', 'Mouse')

In [139]:
print(len(products_tuple))

4

##### max() (Built-in Function)

In [140]:
numbers = (10, 50, 30, 20)

print(max(numbers))

50

##### min() (Built-in Function)

In [141]:
numbers = (10, 50, 30, 20)

print(min(numbers))

10

##### sum() (Built-in Function)

In [142]:
sales = (1200, 1500, 1800)

print(sum(sales))

4500

##### sorted() (Built-in Function)

In [143]:
numbers = (40, 10, 30, 20)

print(sorted(numbers))

[10, 20, 30, 40]

##### Tuple Concatenation (+)  Joins two tuples.

In [144]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5)

result = tuple1 + tuple2

print(result)

(1, 2, 3, 4, 5)

##### Tuple Repetition (*) Repeats a tuple.

In [145]:
days = ("Mon",)

print(days * 3)

('Mon', 'Mon', 'Mon')

##### Membership Operators (in, not in)  Check whether an item exists.

In [146]:
fruits = ("Apple", "Banana", "Mango")

print("Apple" in fruits)
print("Orange" not in fruits)

True
True

##### Tuple Slicing Extract part of a tuple.

In [147]:
numbers = (10, 20, 30, 40, 50)

print(numbers[1:4])

(20, 30, 40)

##### Tuple Unpacking

In [148]:
employee = ("Deepak", "IT", 55000)

name, department, salary = employee

print(name)
print(department)
print(salary)

Deepak
IT
55000

##### Iterate Through a Tuple

In [149]:
colors = ("Red", "Green", "Blue")

for color in colors:
    print(color)

Red
Green
Blue

##### Convert Tuple to List

In [150]:
numbers = (10, 20, 30)

numbers_list = list(numbers)

print(numbers_list)

[10, 20, 30]

##### Convert List to Tuple

In [151]:
numbers = [10, 20, 30]

numbers_tuple = tuple(numbers)

print(numbers_tuple)

(10, 20, 30)

#####  Dictionary - { }

* 2D
* Heterogenous
* Mutable
* Indexing and Slicing is not possible

In [152]:
empty_cart_4 ={}
type(empty_cart_4)

dict

In [154]:
employee = {
    "EmployeeId": 101,
    "EmployeeName": "Deepak",
    "Department": "IT",
    "Salary": 55000,
    "City": "Bangalore"
}

print(employee)

{'EmployeeId': 101, 'EmployeeName': 'Deepak', 'Department': 'IT', 'Salary': 55000, 'City': 'Bangalore'}

In [155]:
print(employee["EmployeeId"])

101

In [156]:
employee["Salary"] = 65000
print(employee)

{'EmployeeId': 101, 'EmployeeName': 'Deepak', 'Department': 'IT', 'Salary': 65000, 'City': 'Bangalore'}

In [157]:
employee["State"] = "Karnataka"
print(employee)

{'EmployeeId': 101, 'EmployeeName': 'Deepak', 'Department': 'IT', 'Salary': 65000, 'City': 'Bangalore', 'State': 'Karnataka'}

In [158]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Department': 'IT',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [159]:
del employee["Department"]
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

#### Dictionary Methods

##### get() Returns the value of a key safely.

In [160]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [161]:
print(employee.get("Salary"))

65000

##### keys() Returns all keys.

In [162]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [163]:
print(employee.keys())

dict_keys(['EmployeeId', 'EmployeeName', 'Salary', 'City', 'State'])

##### values() Returns all values.

In [164]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [165]:
print(employee.values())

dict_values([101, 'Deepak', 65000, 'Bangalore', 'Karnataka'])

##### items() Returns key-value pairs.

In [166]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [167]:
print(employee.items())

dict_items([('EmployeeId', 101), ('EmployeeName', 'Deepak'), ('Salary', 65000), ('City', 'Bangalore'), ('State', 'Karnataka')])

##### update() Updates existing values or adds new ones.

In [168]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 65000,
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [169]:
employee.update({"Department": "IT", "Salary": 55000})

In [170]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 55000,
 'City': 'Bangalore',
 'State': 'Karnataka',
 'Department': 'IT'}

##### pop() Removes a key and returns its value.

In [171]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'Salary': 55000,
 'City': 'Bangalore',
 'State': 'Karnataka',
 'Department': 'IT'}

In [172]:
salary = employee.pop("Salary")
print(salary)
print(employee)

55000
{'EmployeeId': 101, 'EmployeeName': 'Deepak', 'City': 'Bangalore', 'State': 'Karnataka', 'Department': 'IT'}

##### popitem() Removes the last inserted key-value pair.

In [173]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'City': 'Bangalore',
 'State': 'Karnataka',
 'Department': 'IT'}

In [174]:
employee.popitem()

print(employee)

{'EmployeeId': 101, 'EmployeeName': 'Deepak', 'City': 'Bangalore', 'State': 'Karnataka'}

##### copy() Creates a copy of the dictionary.

In [175]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [176]:
employee_new = employee.copy()
employee_new

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'City': 'Bangalore',
 'State': 'Karnataka'}

##### setdefault() Returns the value if the key exists; otherwise inserts the key with a default value.

In [177]:
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'City': 'Bangalore',
 'State': 'Karnataka'}

In [178]:
employee.setdefault("Department", "IT")
employee

{'EmployeeId': 101,
 'EmployeeName': 'Deepak',
 'City': 'Bangalore',
 'State': 'Karnataka',
 'Department': 'IT'}

##### fromkeys() Creates a new dictionary from a list of keys.

In [180]:
keys = ["Name", "Department", "Salary"]

employee = dict.fromkeys(keys, "Not Available")

print(employee)

{'Name': 'Not Available', 'Department': 'Not Available', 'Salary': 'Not Available'}

#### Loop Through Dictionary

In [181]:
employee = {
    "Name": "Deepak",
    "Department": "IT"
}

for key in employee:
    print(key)

Name
Department

In [182]:
for value in employee.values():
    print(value)

Deepak
IT

In [183]:
for key, value in employee.items():
    print(key, ":", value)

Name : Deepak
Department : IT

##### Pandas

In [184]:
import pandas as pd

In [186]:
employee_details = {
    "Employee Id" : ["EMP001","EMP002","EMP003","EMP004","EMP005"],
    "Employee Name" : ["Deepak","Rajendran","Ravi","Priya","Darshan"],
    "Department" : ["IT","HR","HR","IT","IT"],
    "Salary" : ["45000","6000","52000","4000","3000"],
    "City" : ["Bangalore","Chennai","Bangalore","Bangalore","Chennai"],
    }
employee_details

{'Employee Id': ['EMP001', 'EMP002', 'EMP003', 'EMP004', 'EMP005'],
 'Employee Name': ['Deepak', 'Rajendran', 'Ravi', 'Priya', 'Darshan'],
 'Department': ['IT', 'HR', 'HR', 'IT', 'IT'],
 'Salary': ['45000', '6000', '52000', '4000', '3000'],
 'City': ['Bangalore', 'Chennai', 'Bangalore', 'Bangalore', 'Chennai']}

In [187]:
pd.DataFrame(data=employee_details)

  Employee Id Employee Name Department Salary       City
0      EMP001        Deepak         IT  45000  Bangalore
1      EMP002     Rajendran         HR   6000    Chennai
2      EMP003          Ravi         HR  52000  Bangalore
3      EMP004         Priya         IT   4000  Bangalore
4      EMP005       Darshan         IT   3000    Chennai

In [188]:
product_details = {
    "Product Id": ["P101", "P102", "P103", "P104"],
    "Product Name": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [55000, 800, 1200, 10000],
    "Stock": [15, 120, 80, 25],
    "Brand": ["Dell", "Logitech", "HP", "Samsung"]
}

print(product_details)

{'Product Id': ['P101', 'P102', 'P103', 'P104'], 'Product Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 'Price': [55000, 800, 1200, 10000], 'Stock': [15, 120, 80, 25], 'Brand': ['Dell', 'Logitech', 'HP', 'Samsung']}

In [189]:
pd.DataFrame(data=product_details)

  Product Id Product Name  Price  Stock     Brand
0       P101       Laptop  55000     15      Dell
1       P102        Mouse    800    120  Logitech
2       P103     Keyboard   1200     80        HP
3       P104      Monitor  10000     25   Samsung

In [190]:
customer_details = {
    "Customer Id": ["C001", "C002", "C003"],
    "Customer Name": ["Arun", "Meena", "Vijay"],
    "City": ["Bangalore", "Chennai", "Hyderabad"],
    "Phone": ["9876543210", "9876500000", "9999911111"],
    "Email": ["arun@gmail.com", "meena@gmail.com", "vijay@gmail.com"]
}

print(customer_details)

{'Customer Id': ['C001', 'C002', 'C003'], 'Customer Name': ['Arun', 'Meena', 'Vijay'], 'City': ['Bangalore', 'Chennai', 'Hyderabad'], 'Phone': ['9876543210', '9876500000', '9999911111'], 'Email': ['arun@gmail.com', 'meena@gmail.com', 'vijay@gmail.com']}

In [191]:
pd.DataFrame(data=customer_details)

  Customer Id Customer Name       City       Phone            Email
0        C001          Arun  Bangalore  9876543210   arun@gmail.com
1        C002         Meena    Chennai  9876500000  meena@gmail.com
2        C003         Vijay  Hyderabad  9999911111  vijay@gmail.com

In [192]:
vehicle_details = {
    "Vehicle No": ["KA01AB1234", "TN10XY5678", "AP09CD7890"],
    "Driver": ["Ravi", "Kumar", "Suresh"],
    "Route": ["Bangalore-Chennai", "Chennai-Hyderabad", "Mumbai-Pune"],
    "Status": ["Running", "Loading", "Delivered"]
}

print(vehicle_details)

{'Vehicle No': ['KA01AB1234', 'TN10XY5678', 'AP09CD7890'], 'Driver': ['Ravi', 'Kumar', 'Suresh'], 'Route': ['Bangalore-Chennai', 'Chennai-Hyderabad', 'Mumbai-Pune'], 'Status': ['Running', 'Loading', 'Delivered']}

In [193]:
pd.DataFrame(data=customer_details)

  Customer Id Customer Name       City       Phone            Email
0        C001          Arun  Bangalore  9876543210   arun@gmail.com
1        C002         Meena    Chennai  9876500000  meena@gmail.com
2        C003         Vijay  Hyderabad  9999911111  vijay@gmail.com